import type { Metadata } from "next";
import { Lexend, Geist_Mono, EB_Garamond, Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Navbar from "@/components/general/navbar";
import { createClient } from "@/lib/supabase/server";
import prisma from "@/lib/prisma";
import { redirect } from "next/navigation";

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ebGaramond = EB_Garamond({
  variable: "--font-eb-garamond",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  const userData = user
    ? await prisma.user.findUnique({
        where: {
          id: user.id,
        },
        include: {
          subscription: true,
        },
      })
    : null;

  return (
    <html lang="en" className="">
      <body
        className={`${lexend.variable} ${inter.variable} ${geistMono.variable} ${ebGaramond.variable} ${lexend.className}   antialiased`}
      >
        {/* <Navbar/> */}
        <Providers user={userData}>{children}</Providers>
      </body>
    </html>
  );
}
